package:
  name: dynare-preprocessor-pylib
  version: 0.0.0.dev0

context:
  name: dynare-preprocessor-pylib
  version: 0.0.0.dev0

source:
  url: https://git.dynare.org/albop/preprocessor/-/archive/pylib/preprocessor-pylib.tar.gz
  sha256: 7a485514a09bf9a03986670499c08876124f2c7e6bb3b114cc92ce9f3065fe6f

build:
  number: 0

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - meson
    - bison
    - flex
    - libboost-headers
    - pthread-stubs
    - pkg-config

  host:
    - pybind11
    - libpython

test:
  files:
    - example1.mod

about:
  home: https://www.dynare.org/
  summary: Dynare preprocessor
  description: Preprocessor for Dynare, a platform for handling a wide class of economic models.
  doc_url: https://www.dynare.org/manual/
  dev_url: https://git.dynare.org/Dynare/preprocessor
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING

extra:
  recipe-maintainers:
    - albop
    - svillemot
